# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$python\
$character
"""

right_format = """
$git_status\
$git_state\
$git_branch\
$git_commit
"""

add_newline = false

[username]
format = '[$user]($style)'
style_user = ''

[hostname]
format = '@$hostname '

[directory]
style = 'bold green'
truncate_to_repo = false

[python]
format = '[\[${pyenv_prefix}(${version})( \($virtualenv\))\] ]($style)'
style = ''

[character]
success_symbol = '[>](bold blue)'
error_symbol = '[>](bold red)'

[git_status]
format = '((${ahead_behind} )($conflicted$untracked$modified$staged ))'
style = ''

ahead = '[+$count](green)'
behind = '[-$count](red)'
diverged = '[+$ahead_count](bold green)[-$behind_count](bold red)'

stashed = ''
staged = '[*](bold green)'
modified = '[*](bold yellow)'
untracked = '[*](bold red)'
conflicted = '[*](bold magenta)'

[git_branch]
format = '[$branch(:$remote_branch)]($style)'
style = ''
